apiVersion: v1
kind: ReplicationController
metadata:
  name: myrc1
spec:
  replicas: 3
  selector:
    app: web
  template:
    metadata:
      name: "mypod1"
      labels:
        app: web
    spec:
      containers:
      - image: "myrc1"
        image: "vimal13/apache-webserver-php"
