Storage Class:
  NFS Server:
  mkdir /mydata 
  cat vi /etc/exports > /mydata   *(rw,no_root_squash or insecure)
  systemctl start nfs-server
  exportfs -v -r
cat /var/log/messages 

Client: mount IP:/mydata /mnt/data


apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
spec:
  storageClassName: ""
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
spec:
  storageClassName: ""
  capacity:
      storage: 10Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    server: "/mydata"
    path: "/mydata"