- hosts: 172.31.40.162
  become: yes
  tasks:
  - package:
      name: "httpd"
      state: present
  - file:
      state: directory
      path: "/var/www/lw"
  - copy:
      dest: /etc/httpd/conf.d/lw.conf
      src: "lw.conf"
  - copy:
      dest: /var/www/lw/index.html
      content: "New Website"
  - service:
      name: httpd
      state: restarted
      enabled: yes
