- hosts: WebServer
  become: yes
  tasks:	 
  - package:
      name: "httpd"
      state: present	  
  - copy:
      dest: "/var/www/html/index.html"
      content: "Welcome to My Secure Page"
  - replace:
      path: "/etc/httpd/conf/httpd.conf"
      regexp: "AllowOverride None"
      replace: "AllowOverride AuthConfig"
  - copy:
      dest: /var/www/html/.htaccess
      src: /root/ansible/.htaccess
  - package:
      name: "python-pip"
  - pip:
      name: "passlib"
  - htpasswd:
      path: "/etc/www.htpasswd"
      name: "Prashant"
      password: "redhat"
  - service:
      name: httpd
      state: restarted
      enabled: yes
