- hosts: docker
  become: yes
  tasks:
  - name: Seting Up Docker
    yum_repository:
      name: dockername
      description: docker description
      baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/
      gpgcheck: no
  - command: "yum install docker-ce -y --nobest"

