- hosts: all
  tasks:
  - name: install wget in RedHat
    yum:
      name: wget
      state: present
    when: ansible_facts['os_family'] == "RedHat"
  - name: install wget Debian
    apt:
      name: wget
      state: present
    when: ansible_facts['os_family'] == "Debian"
