apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nodeappds
spec:
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      name: nodejspod
      labels:
        app: nodeapp
    spec:
      containers:
      - name: nodecontainer
        image: prashhantss/nodejs-app:1
        ports:
        - containerPort: 9981
---
apiVersion: v1
kind: Service
metadata:
  name: nodeappsvc
spec:
  type: NodePort
  selector:
    app: nodeapp
  ports:
  - port: 80
    targetPort: 9981
