apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-pv1
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 172.31.95.189
    path: "/mnt/share"
