apiVersion: v1
kind: Secret
metadata:
  name: springappsecret
type: Opaque
stringData:
  mongopassword: qadb@123






#kubectl create secret generic springappsecret --from-literal=mongopassword=devdb@123
