- hosts: all
  become: yes
  tasks:	 
  - package:
      name: "httpd"
      state: present	  
  - copy:
      dest: "/var/www/html/index.html"
      content: "Secure Page"
  - replace:
      path: "/etc/httpd/conf/httpd.conf"
      regexp: "AllowOverride None"
      replace: "AllowOverride AuthConfig"
  - copy:
      dest: /var/www/html/.htaccess"
      src: ".htaccess"
  - package:
      name: "python-pip"
  - pip:
      name: "passlib"
  - htpasswd:
      path: "/etc/www.passwd"
      name: "Prashant"
      password: "redhat"
  - service:
      name: httpd
      enabled: yes
